
FROM node:18.14 AS build

WORKDIR /app

COPY . .

RUN npm install && \
    npm run build

FROM nginx:alpine

EXPOSE 5173

COPY --from=build /app/dist /usr/share/nginx/html/

COPY /nginx.conf /etc/nginx/conf.d/default.conf


