version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - projet-devops
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - projet-devops
    ports:
      - "3000:4000"
networks:
  projet-devops:
    driver: bridge
