# Use a Node.js base image
FROM node:18.16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend source code to the container
COPY . .

# Expose the port your app runs on 
EXPOSE 5000

# Command to run the backend server
CMD ["node", "index.js"]

